#!/usr/bin/env bash
# Local development harness for the AI automatizace add-on.
#
# Resets devdata/, starts the mock Supervisor/Core (8124), builds and starts the add-on (8099)
# and the ingress emulation proxy (8098). Ctrl+C stops everything.
#
# Env options:
#   SEED=full|minimal   seed config to copy (default full = devtools/seed-config)
#   KEEP_DATA=1         do not reset devdata/ (keeps chats, history, codex homes)
#   SKIP_BUILD=1        do not run `npm run build`
#   CODEX_BIN=<path>    codex binary (default: fake Codex app-server fixture)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
APP_DIR="${REPO_ROOT}/ai_automation/app"
DEV_DATA="${REPO_ROOT}/devdata"
CONFIG_DIR="${DEV_DATA}/config"
DATA_DIR="${DEV_DATA}/data"

MOCK_PORT=8124
ADDON_PORT=8099
INGRESS_PORT=8098
SUPERVISOR_TOKEN_VALUE='dev-supervisor-token'
INGRESS_URL="http://127.0.0.1:${INGRESS_PORT}/api/hassio_ingress/devtoken/"
FAKE_CODEX="${APP_DIR}/test/fixtures/fake-codex.mjs"

case "${SEED:-full}" in
    full) SEED_DIR="${SCRIPT_DIR}/seed-config" ;;
    minimal) SEED_DIR="${SCRIPT_DIR}/seed-config-minimal" ;;
    *) echo "Unknown SEED '${SEED}' (use full or minimal)" >&2; exit 1 ;;
esac

# secrets.yaml is not committed (public repo); generate obviously fake values for the mock.
write_fake_secrets() {
    if [ ! -f "$1" ]; then
        printf '# Fake development secrets (generated by devtools)\nrecorder_db_url: "sqlite:///fake-dev.db"\n' > "$1"
    fi
}

CHILD_PIDS=()

cleanup() {
    trap - EXIT INT TERM
    echo
    echo "[dev] stopping..."
    for pid in "${CHILD_PIDS[@]}"; do
        kill "${pid}" 2>/dev/null || true
    done
    wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

log() {
    echo "[dev] $*"
}

wait_for_port() {
    local port="$1" name="$2"
    for _ in $(seq 1 50); do
        if (exec 3<>"/dev/tcp/127.0.0.1/${port}") 2>/dev/null; then
            return 0
        fi
        sleep 0.2
    done
    echo "[dev] ${name} did not start on port ${port}" >&2
    exit 1
}

reset_devdata() {
    if [[ "${KEEP_DATA:-0}" == "1" && -d "${CONFIG_DIR}" ]]; then
        log "KEEP_DATA=1 -> keeping ${DEV_DATA}"
        return
    fi
    log "resetting ${DEV_DATA} from $(basename "${SEED_DIR}")"
    rm -rf -- "${DEV_DATA}"
    mkdir -p "${CONFIG_DIR}" "${DATA_DIR}"
    cp -a "${SEED_DIR}/." "${CONFIG_DIR}/"
    write_fake_secrets "${CONFIG_DIR}/secrets.yaml"
    printf '{\n    "default_model": null,\n    "default_reasoning": null,\n    "log_level": "debug"\n}\n' > "${DATA_DIR}/options.json"
}

install_dependencies() {
    if [[ ! -d "${SCRIPT_DIR}/node_modules/yaml" ]]; then
        log "installing devtools dependencies"
        (cd "${SCRIPT_DIR}" && npm install --no-audit --no-fund)
    fi
    if [[ ! -d "${APP_DIR}/node_modules/ws" ]]; then
        log "installing app dependencies"
        (cd "${APP_DIR}" && npm install --no-audit --no-fund)
    fi
}

build_app() {
    if [[ "${SKIP_BUILD:-0}" == "1" ]]; then
        log "SKIP_BUILD=1 -> using existing dist/"
        return
    fi
    log "building add-on app"
    (cd "${APP_DIR}" && npm run build)
}

start_mock() {
    log "starting mock Supervisor on :${MOCK_PORT}"
    HA_CONFIG_DIR="${CONFIG_DIR}" MOCK_PORT="${MOCK_PORT}" MOCK_TOKEN="${SUPERVISOR_TOKEN_VALUE}" \
        node "${SCRIPT_DIR}/mock-supervisor.mjs" &
    CHILD_PIDS+=("$!")
    wait_for_port "${MOCK_PORT}" 'mock-supervisor'
}

start_addon() {
    local codex_bin="${CODEX_BIN:-${FAKE_CODEX}}"
    if [[ "${codex_bin}" == "${FAKE_CODEX}" && ! -f "${FAKE_CODEX}" ]]; then
        log "WARNING: ${FAKE_CODEX} not found - Codex features will fail"
    fi
    log "starting add-on on :${ADDON_PORT} (CODEX_BIN=${codex_bin})"
    HA_CONFIG_DIR="${CONFIG_DIR}" \
    DATA_DIR="${DATA_DIR}" \
    SUPERVISOR_URL="http://127.0.0.1:${MOCK_PORT}" \
    SUPERVISOR_TOKEN="${SUPERVISOR_TOKEN_VALUE}" \
    CODEX_BIN="${codex_bin}" \
    PORT="${ADDON_PORT}" \
    ALLOW_ANY_ORIGIN_IP=1 \
    PATH="${APP_DIR}/bin:${PATH}" \
        node "${APP_DIR}/dist/server/main.js" &
    CHILD_PIDS+=("$!")
    wait_for_port "${ADDON_PORT}" 'add-on server'
}

start_proxy() {
    log "starting ingress proxy on :${INGRESS_PORT}"
    INGRESS_PORT="${INGRESS_PORT}" ADDON_PORT="${ADDON_PORT}" node "${SCRIPT_DIR}/ingress-proxy.mjs" &
    CHILD_PIDS+=("$!")
    wait_for_port "${INGRESS_PORT}" 'ingress proxy'
}

reset_devdata
install_dependencies
build_app
start_mock
start_addon
start_proxy

cat <<EOF

[dev] ready
      UI (ingress emulation): ${INGRESS_URL}
      second user:            ${INGRESS_URL}?user=dev-user-2
      add-on direct:          http://127.0.0.1:${ADDON_PORT}/
      mock supervisor:        http://127.0.0.1:${MOCK_PORT}/ (token ${SUPERVISOR_TOKEN_VALUE})
      service call log:       http://127.0.0.1:${MOCK_PORT}/_mock/calls
      haos-tool:              SUPERVISOR_URL=http://127.0.0.1:${MOCK_PORT} SUPERVISOR_TOKEN=${SUPERVISOR_TOKEN_VALUE} HA_CONFIG_DIR=${CONFIG_DIR} ${APP_DIR}/bin/haos-tool entities
      Press Ctrl+C to stop.
EOF

# Exit (and clean up) as soon as any child dies.
wait -n
log "a child process exited"
